name: "Terraform — Azure Deploy (Plan + Apply, OIDC Backend)"

on:
  push:
    branches: [ main ]

env:
  TF_WORKING_DIR: '.'
  TF_PLAN_FILE: 'tfplan.bin'

jobs:
  terraform:
    name: Plan & Apply
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # required for OIDC

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.13.3'
          terraform_wrapper: false

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Auto-format Terraform
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -recursive

      - name: Terraform Init (remote backend via AAD)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -reconfigure \
            -backend-config="use_azuread_auth=true" \
            -backend-config="resource_group_name=${{ secrets.TF_BACKEND_RESOURCE_GROUP }}" \
            -backend-config="storage_account_name=${{ secrets.TF_BACKEND_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ secrets.TF_BACKEND_CONTAINER }}" \
            -backend-config="key=${{ secrets.TF_BACKEND_KEY }}"

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan (save planfile)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan \
            -out="${{ env.TF_PLAN_FILE }}" \
            -input=false \
            -var="admin_password=${{ secrets.ADMIN_PASSWORD }}" \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Show Terraform Plan (text)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform show "${{ env.TF_PLAN_FILE }}"

      - name: Export Plan JSON (artifact)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform show -json "${{ env.TF_PLAN_FILE }}" > plan.json

      - name: Upload plan.json
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-json
          path: plan.json
          if-no-files-found: error

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve "${{ env.TF_PLAN_FILE }}"

      - name: Show State & Outputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo '--- Terraform State List ---'
          terraform state list || echo '(no state)'
          echo '--- Terraform Outputs ---'
          terraform output || echo '(no outputs)'
          echo '--- Outputs (JSON) ---'
          terraform output -json
