name: "Terraform — Azure Destroy (OIDC Backend)"

on:
  workflow_dispatch:  # Manual trigger

env:
  TF_WORKING_DIR: '.'
  TF_PLAN_FILE: 'tfplan-destroy.bin'

jobs:
  terraform-destroy:
    name: Plan & Destroy
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write  # Required for OIDC

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.13.3'
          terraform_wrapper: false

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init (remote backend via AAD)
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: |
          terraform init -reconfigure `
            -backend-config="use_azuread_auth=true" `
            -backend-config="resource_group_name=${{ secrets.TF_BACKEND_RESOURCE_GROUP }}" `
            -backend-config="storage_account_name=${{ secrets.TF_BACKEND_STORAGE_ACCOUNT }}" `
            -backend-config="container_name=${{ secrets.TF_BACKEND_CONTAINER }}" `
            -backend-config="key=vnet1.tfstate"

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: terraform validate

      - name: Terraform Plan Destroy (save plan)
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: |
          terraform plan -destroy `
            -out="${{ env.TF_PLAN_FILE }}" `
            -input=false

      - name: Show Destroy Plan (text)
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: terraform show "${{ env.TF_PLAN_FILE }}"

      - name: Export Destroy Plan JSON (artifact)
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: terraform show -json "${{ env.TF_PLAN_FILE }}" > destroy-plan.json

      - name: Upload destroy plan JSON
        uses: actions/upload-artifact@v4
        with:
          name: terraform-destroy-plan-json
          path: destroy-plan.json
          if-no-files-found: error

      - name: Terraform Apply Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: terraform apply -auto-approve "${{ env.TF_PLAN_FILE }}"

      - name: Show State & Outputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: |
          Write-Host '--- Terraform State List ---'
          terraform state list || Write-Host '(no state)'
          Write-Host '--- Terraform Outputs ---'
          terraform output || Write-Host '(no outputs)'
          Write-Host '--- Outputs (JSON) ---'
          terraform output -json
