name: "Terraform — Azure Deploy (Debug & Apply)"

on:
  push:
    branches:
      - main

env:
  TF_WORKING_DIR: '.'           # Adjust if your Terraform root lives in a subfolder
  TF_PLAN_FILE: 'tfplan.bin'

jobs:
  terraform:
    name: Plan & Apply (with Debug)
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Validate module folder existence
      - name: Validate module directories
        shell: pwsh
        run: |
          Write-Host "Checking existence of modules/vnet and modules/windows-vm"
          if (-not (Test-Path "./modules/vnet")) {
            Write-Error "❌ Module folder ./modules/vnet does not exist!"
            exit 1
          }
          if (-not (Test-Path "./modules/windows-vm")) {
            Write-Error "❌ Module folder ./modules/windows-vm does not exist!"
            exit 1
          }
          Write-Host "✅ Required module directories found."

      # Debug: list files
      - name: Debug file structure
        shell: pwsh
        run: |
          Write-Host "=== Listing root directory ==="
          dir .\ -Recurse
          Write-Host "=== Listing modules directory ==="
          dir .\modules -Recurse

      # Setup Terraform tool
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Clean Terraform local cache
      - name: Clean Terraform cache
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: |
          if (Test-Path .terraform) {
            Remove-Item -Recurse -Force .terraform
          }
          if (Test-Path .terraform.lock.hcl) {
            Remove-Item .terraform.lock.hcl
          }
          Write-Host "✅ Cleaned Terraform cache."

      # Terraform init
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -reconfigure

      # Debug after init: check modules folder
      - name: Post-init modules folder check
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: |
          Write-Host "=== Modules folder contents after init ==="
          dir .\modules -Recurse

      # Terraform format check
      - name: Terraform Format
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -recursive

      # Terraform validate
      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      # Terraform plan
      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan -out=${{ env.TF_PLAN_FILE }} `
            -var="admin_password=${{ secrets.ADMIN_PASSWORD }}" `
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" `
            -input=false

      # Show plan in text
      - name: Show Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform show ${TF_PLAN_FILE}

      # Export plan JSON
      - name: Export Plan JSON
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform show -json ${TF_PLAN_FILE} > plan.json

      # Upload plan.json artifact
      - name: Upload plan.json
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-json
          path: plan.json

      # Inspect plan JSON summary
      - name: Inspect Plan JSON Summary
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: |
          $json = Get-Content -Raw plan.json | ConvertFrom-Json
          Write-Host "===== Plan JSON Summary ====="
          if ($null -eq $json.module_calls) {
            Write-Host "No modules found in plan.json.module_calls"
          } else {
            Write-Host "Modules recognized: " + ($json.module_calls.Keys -join ", ")
          }
          if ($null -eq $json.resource_changes) {
            Write-Host "resource_changes is null or empty"
          } else {
            Write-Host "Number of resource_changes: $($json.resource_changes.Count)"
            foreach ($rc in $json.resource_changes) {
              Write-Host " • $($rc.address) (change: $($rc.change.actions -join ', '))"
            }
          }

      # Terraform apply (only if there are resource changes)
      - name: Terraform Apply (Conditional)
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: |
          $json = Get-Content -Raw plan.json | ConvertFrom-Json
          if ($null -eq $json.resource_changes -or $json.resource_changes.Count -eq 0) {
            Write-Host "ℹ️ No changes detected, skipping terraform apply."
            exit 0
          } else {
            terraform apply -auto-approve ${TF_PLAN_FILE}
          }

      # Debug state & outputs
      - name: Debug State & Outputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo "--- Terraform State List ---"
          terraform state list || echo "(no state)"
          echo "--- Terraform Outputs ---"
          terraform output || echo "(no outputs)"

      # Dump all outputs as JSON
      - name: Dump All Outputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: |
          Write-Host "=== Terraform outputs raw ==="
          $raw = terraform output -json
          if ($raw) {
            $obj = $raw | ConvertFrom-Json
            $obj | ConvertTo-Json -Depth 5
          } else {
            Write-Host "No outputs returned (raw JSON empty)."
          }

      # Validate subnet_id output
      - name: Validate Subnet Output
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: |
          $subnetId = terraform output -raw subnet_id 2>$null
          Write-Host "Subnet ID (raw): '$subnetId'"
          if ([string]::IsNullOrEmpty($subnetId)) {
            Write-Error "❌ subnet_id output is empty — VNet module may not have been created or output defined incorrectly."
            exit 1
          } else {
            Write-Host "✅ Subnet ID: $subnetId"
          }

      # Show VM outputs
      - name: Show VM Outputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        shell: pwsh
        run: |
          Write-Host "=== VM Outputs ==="
          $vmId = terraform output -raw vm_id 2>$null
          $vmPriv = terraform output -raw vm_private_ip 2>$null
          $vmPub = terraform output -raw vm_public_ip 2>$null
          Write-Host "VM ID: '$vmId'"
          Write-Host "VM Private IP: '$vmPriv'"
          Write-Host "VM Public IP: '$vmPub'"
